/* © 2026 Akash Saha. AI Design Mastery. All rights reserved. */

const LESSONS = {
  1: {num: 1, title: 'Day 1: Master the 5 Layers Framework', duration: '45 min', phase: 1, concept: `The 5 Layers Framework is the foundation of professional AI prompts. Every great image has: (1) a clear Subject, (2) meaningful Action, (3) realistic Environment, (4) purposeful Lighting, and (5) cohesive Style. When you control all 5, you control the entire image.`, layer1: {name: 'Subject', desc: 'Who or what is the main focus? (person, object, animal - be specific about age, appearance, pose)'}, layer2: {name: 'Action', desc: 'What are they doing? (not just "standing" - give them purpose: working, jumping, reaching)'}, layer3: {name: 'Environment', desc: 'Where does this happen? (real place with details: modern office, cozy cafe, mountain peak)'}, layer4: {name: 'Lighting', desc: 'How does light shape the mood? (golden hour warmth, harsh drama, soft diffused, neon night)'}, layer5: {name: 'Style', desc: 'What\'s the artistic direction? (cinematic, minimalist, hyper-realistic, watercolor, 3D render)'}, assignment: {brief: 'Create a professional hero image prompt for a productivity app using all 5 Layers', task: `Your task: Write a detailed prompt for an AI image generator that shows someone using your productivity app productively. The prompt must include a specific Subject (not just "person"), clear Action (not just "sitting"), realistic Environment, purposeful Lighting, and cohesive Style.`, goodExample: 'A professional woman in her late 20s, focused and typing on keyboard at minimalist standing desk, contemporary home office with plants and natural light, morning golden sunlight streaming through windows, warm modern aesthetic with clean lines and calm colors', badExample: '❌ "A person working on laptop. Make it nice with good lighting and professional colors"', requirements: ['✓ Subject: Specific age range, appearance, body language (not generic "person")', '✓ Action: Purposeful activity - focused work, not passive sitting', '✓ Environment: Real, matching the app\'s purpose (home office, coworking, coffee shop)', '✓ Lighting: Named light source and color temperature affecting mood', '✓ Style: Cohesive aesthetic direction (no conflicting styles)'], successCriteria: ['✓ AI can generate a recognizable productive scene', '✓ All 5 layers are visible in the result', '✓ Image feels professional, not amateur or chaotic', '✓ Each layer contributes to the overall mood', '✓ Prompt is detailed enough to be reproducible']}, videos: [{title: 'The 5 Layers: Foundation of Professional Prompts', url: 'https://youtu.be/...', duration: '12 min'}, {title: 'How Professional Photographers Think (AI Needs Same Info)', url: 'https://youtu.be/...', duration: '8 min'}, {title: 'Common Mistakes: Vague Subjects & Generic Styles', url: 'https://youtu.be/...', duration: '6 min'}], builder: 'prompt-layers', tools: ['Nano Banana Pro', 'ChatGPT Images', 'Midjourney v8']
  },
  2: {num: 2, title: 'Day 2: Visual Hierarchy in AI Images', duration: '45 min', phase: 1, concept: `Visual hierarchy tells the viewer what to look at first, second, third. In AI prompts, you control hierarchy through: size (bigger = more important), focus (sharp = important, blurred = background), color (bright/warm = important, muted/cool = background), contrast (high contrast = attention-grabbing), and light (bright areas draw eyes).`, assignment: {brief: 'Create a prompt where one element unmistakably dominates the composition', task: `Your task: Write a prompt for a product or hero image where the main subject is impossible to miss. Use size, sharpness, color contrast, and lighting to guide the viewer's eye. The background should support but never compete.`, goodExample: 'Large, sharp product in center of frame with dramatic spotlight from above, soft blurred lifestyle background in complementary but muted tones, deep dark background makes product glow, glossy finish catches light, viewer\'s eye goes directly to product', badExample: '❌ "Product image with good focus and background stuff"', requirements: ['✓ Clearly name the primary focal point (what\'s most important)', '✓ Explain how it stands out (size? sharpness? brightness? color?)', '✓ Describe the background (blurred, darker, simpler - supporting role)', '✓ Specify lighting direction (how it highlights the main element)', '✓ Define negative space (what\'s NOT there that could distract)'], successCriteria: ['✓ Main subject is unmistakably the focus', '✓ Viewer knows where to look immediately', '✓ Background supports without competing', '✓ Lighting is purposeful (creates hierarchy)', '✓ Composition feels intentional and professional']}, videos: [{title: 'Visual Hierarchy: The Psychology of Where Eyes Go', url: 'https://youtu.be/...', duration: '10 min'}, {title: 'Using Blur, Color & Light to Create Focus', url: 'https://youtu.be/...', duration: '9 min'}], builder: 'prompt-hierarchy', tools: ['Nano Banana Pro', 'Leonardo AI', 'Ideogram 2.0']
  },
  3: {num: 3, title: 'Day 3: Character Consistency Across Variations', duration: '50 min', phase: 1, concept: `When you create a campaign with multiple images of the same character, consistency is critical. You must separate immutable features (face, age, body) from mutable elements (clothing, location, pose). The character must be recognizable in every image.`, assignment: {brief: 'Write a prompt for 3-4 campaign variations with the same consistent character', task: `Your task: Create a detailed character description that will stay the same across 3-4 different scenarios. Then describe each scenario variation. The character should be instantly recognizable in all images while in different contexts.`, goodExample: 'Asian female, age 28-32, shoulder-length black hair with subtle layers, warm brown eyes, confident smile, athletic build. Immutable. VARIATION 1: Coffee shop morning - casual sweater, holding latte, natural light. VARIATION 2: Office afternoon - business casual, at desk, professional lighting. VARIATION 3: Evening workout - athletic wear, focused expression, gym setting. Same person, different scenarios.', badExample: '❌ "Woman in different poses and clothes. Make sure she looks similar"', requirements: ['✓ Name immutable features in detail (age, race, facial features, body type)', '✓ Specify photography style (consistent lighting approach, camera feel)', '✓ Define color grading (consistent mood/tone across variations)', '✓ List mutable elements (what changes per scenario)', '✓ Explain the visual thread (what ties all images together)'], successCriteria: ['✓ Same character is recognizable in all variations', '✓ Character\'s personality is consistent (not wildly different moods)', '✓ Photography style feels cohesive (same photographer?)', '✓ Color treatment is similar (not drastically different)', '✓ Campaign feels unified, not random different people']}, videos: [{title: 'Character Consistency: Immutable vs Mutable', url: 'https://youtu.be/...', duration: '11 min'}, {title: 'Lighting & Color Consistency Across Scenes', url: 'https://youtu.be/...', duration: '10 min'}], builder: 'prompt-character', tools: ['Midjourney v8', 'ChatGPT Images', 'Nano Banana Pro']
  },
  4: {num: 4, title: 'Day 4: Color Palettes That Don\'t Clash', duration: '45 min', phase: 1, concept: `Color is one of the biggest differentiators between amateur and professional AI images. Specific color names, proper ratios, and understanding color theory prevent muddy, clashing results. A luxury brand needs different colors than a playful startup.`, assignment: {brief: 'Create a color-focused prompt that avoids muddy mixing and clashing', task: `Your task: Write a prompt where you explicitly name 3-4 specific colors, assign them percentages, and explain their relationship. Include colors to AVOID so the AI doesn't accidentally add wrong hues.`, goodExample: 'Elegant palette: 60% warm cream/ivory background, 30% deep navy accents and text, 10% gold metallic highlights and borders. Navy provides professional contrast against cream without being cold. Gold adds luxury without overwhelming. Avoid: bright colors, pastels, warm oranges that feel cheap, neon anything.', badExample: '❌ "Use nice colors that work well together and look luxury"', requirements: ['✓ Name specific colors, not generic categories (sage green, not green)', '✓ Assign percentages showing dominant vs accent colors', '✓ Explain why colors work together (color theory - complementary, monochromatic, etc.)', '✓ Connect to emotion/brand feeling (luxury feels different than playful)', '✓ List 2-3 colors to explicitly avoid'], successCriteria: ['✓ Colors are precisely named (not vague)', '✓ Percentages guide composition naturally', '✓ Color choice matches brand/mood intent', '✓ Result avoids muddy or clashing colors', '✓ Palette feels intentional and professional']}, videos: [{title: 'Color Theory for AI Prompts: Why It Matters', url: 'https://youtu.be/...', duration: '12 min'}, {title: 'Avoiding Muddy Mixes: Color Specificity Guide', url: 'https://youtu.be/...', duration: '9 min'}], builder: 'prompt-color', tools: ['Nano Banana Pro', 'Leonardo AI', 'ChatGPT Images']
  },
  5: {num: 5, title: 'Day 5: Typography as a Design Element', duration: '50 min', phase: 1, concept: `Typography in AI prompts isn't about typing fancy - it's about using font choice to communicate emotion and hierarchy. Serif fonts feel classic. Sans-serif feels modern. Script feels elegant. The AI needs to know not just what text says, but what it should communicate visually.`, assignment: {brief: 'Write a prompt where typography is a main design element communicating genre and mood', task: `Your task: Create a book cover or poster prompt where typography (font, size, color, placement) does the heavy lifting of communicating genre, mood, and hierarchy. The text must be as carefully designed as any visual element.`, goodExample: 'Book cover - Title in elegant serif font (Georgia-style), warm gold color, positioned upper-left on dark moody background. Author name in small, refined sans-serif, silver color, bottom-right. Serif suggests classic literature while sans-serif suggests contemporary author. Typography creates sophisticated, mysterious mood. Illustration behind text doesn\'t overwhelm the carefully placed letters.', badExample: '❌ "Add text on the cover that looks cool and dramatic"', requirements: ['✓ Specify font families (serif vs sans-serif, and style if possible)', '✓ Explain why this font communicates the genre/mood', '✓ Name text colors (not just "white" - warm, cool, metallic, shadow)', '✓ Define hierarchy (what\'s largest? what matters most?)', '✓ Describe placement (why that position on the page)'], successCriteria: ['✓ Font choice matches genre (serif for classic, sans for modern)', '✓ Visual hierarchy is clear (reader knows title, then author)', '✓ Text is readable against background (good contrast)', '✓ Typography reinforces mood (doesn\'t conflict with image)', '✓ Text placement feels intentional (part of design, not an afterthought)']}, videos: [{title: 'Font Psychology: What Fonts Communicate', url: 'https://youtu.be/...', duration: '10 min'}, {title: 'Typography Hierarchy in Visual Design', url: 'https://youtu.be/...', duration: '9 min'}], builder: 'prompt-typography', tools: ['Nano Banana Pro', 'Ideogram 2.0', 'ChatGPT Images']
  },
  6: {num: 6, title: 'Day 6: Cinematic Lighting Techniques', duration: '50 min', phase: 1, assignment: {brief: 'Create a dramatic cinematic lighting setup for a specific mood', task: 'Write a prompt where lighting is the star - specify light sources, color temperature, shadows, and atmosphere to create mood.', goodExample: 'Noir thriller scene: harsh single light source from upper-left creating deep facial shadows, cool blue ambient light from distant window, warm tungsten lamp light mixing in, high contrast with bright highlights and inky shadows, volumetric light visible through subtle smoke, desaturated colors except red neon sign glowing off wet pavement', badExample: '❌ "Dark dramatic lighting with shadows"', requirements: ['✓ Identify primary light source (where\'s the main light from?)', '✓ Name color temperature (warm/cool and emotional effect)', '✓ Describe shadow quality (hard vs soft, purpose of shadows)', '✓ Specify atmosphere (fog, smoke, dust - affects light scatter)', '✓ Include practical lights (lamps, signs, screens that exist in-world)'], successCriteria: ['✓ Light source is identifiable', '✓ Shadows create mood (not just darkness)', '✓ Color temperature is consistent and intentional', '✓ Atmosphere feels cinematic (like a professional film)', '✓ Lighting serves emotional narrative']}, tools: ['Nano Banana Pro', 'Midjourney v8', 'Leonardo AI']
  },
  7: {num: 7, title: 'Day 7: Campaign Consistency Across Platforms', duration: '50 min', phase: 1, assignment: {brief: 'Define visual language that works across Instagram, billboards, and websites', task: 'Create a visual campaign language that ties together multiple platform variations - Instagram posts, TikTok videos, billboards, and web. Specify what stays consistent.', goodExample: 'Visual language: flat design with geometric shapes, pastel colors (soft pink, mint, cream), bold sans-serif, playful but professional, lots of white space, natural lifestyle + graphic elements mixed, Gen-Z aesthetic but timeless (2+ years), photo-illustration hybrid style, consistent 45-degree angle layouts, always includes hands or human touch', badExample: '❌ "Make it look cool and modern for all platforms"', requirements: ['✓ Define aesthetic category (flat, 3D, photography, illustration, hybrid)', '✓ List 3-4 core elements that repeat across all variations', '✓ Name target audience specifically (not just "young people")', '✓ Explain tone (professional, playful, luxury, sustainable, etc.)', '✓ State what to avoid (trends, what feels dated)'], successCriteria: ['✓ Visual language is instantly recognizable', '✓ Aesthetic will stay relevant 2+ years', '✓ Works on tiny phone screen AND large billboard', '✓ Target audience sees themselves reflected', '✓ Brand personality is clear and consistent']}, tools: ['Nano Banana Pro', 'ChatGPT Images', 'Ideogram 2.0']
  },
  8: {num: 8, title: 'Day 8: Subject Specificity', duration: '45 min', phase: 1, assignment: {brief: 'Master the art of specific subject descriptions', task: 'Write prompts for 3 different people, each with unique, non-generic descriptions', goodExample: 'Latina woman, age 32, warm brown skin tone, black hair in high ponytail, athletic dancer build, intense focused expression, traditional clothing mixed with modern streetwear', badExample: '❌ "A woman"', requirements: ['✓ Age range (not generic)', '✓ Ethnicity/appearance details', '✓ Body type/posture', '✓ Facial expression/emotion', '✓ Clothing style'], successCriteria: ['✓ AI generates specific person', '✓ Recognizable in variations', '✓ Personality shines through', '✓ Professional appearance quality']}, tools: ['Midjourney v8', 'ChatGPT Images', 'Nano Banana Pro']
  },
  9: {num: 9, title: 'Day 9: Action Verbs in Prompts', duration: '45 min', phase: 1, assignment: {brief: 'Use dynamic action words to create movement', task: 'Write prompts where action is clear and purposeful', goodExample: 'Figure leaping mid-air, arms extended, fabric flowing around them, captured mid-jump in dynamic motion, weight shifting, muscles engaged, frozen in moment of flight', badExample: '❌ "Person in air"', requirements: ['✓ Specific action verb', '✓ Physics/momentum', '✓ Body positioning', '✓ Captured moment', '✓ Implied motion'], successCriteria: ['✓ Movement is visible and clear', '✓ Energy/intention comes through', '✓ Dynamic not static', '✓ Realistic physics']}, tools: ['Nano Banana Pro', 'Kling 2.6', 'Midjourney v8']
  },
  10: {num: 10, title: 'Day 10: Environmental Storytelling', duration: '50 min', phase: 1, assignment: {brief: 'Use environment details to tell the character\'s story', task: 'Create prompts where the setting reveals character background and narrative', goodExample: 'Artist studio: canvases at various stages, paint-splattered floors, north-facing windows, mood lighting from old lamps, organized chaos showing years of creative work, details hint at artist\'s aesthetic and struggles', badExample: '❌ "Art studio"', requirements: ['✓ Specific details about space', '✓ Signs of occupation/use', '✓ Props that tell story', '✓ Lighting that creates mood', '✓ Subtle narrative clues'], successCriteria: ['✓ Setting feels lived-in and real', '✓ Story emerges from details', '✓ Mood is tangible', '✓ Character fits environment', '✓ Believable and specific']}, tools: ['Nano Banana Pro', 'Leonardo AI', 'ChatGPT Images']
  },
  11: {num: 11, title: 'Day 11: Lighting Color Temperature', duration: '45 min', phase: 1, assignment: {brief: 'Use warm/cool lighting to control mood', task: 'Write prompts where color temperature explicitly creates emotional response', goodExample: 'Cozy evening: warm golden tungsten lighting from table lamp, soft orange/amber color casting long shadows, intimate atmosphere feeling safe and warm, muted cool shadows creating depth, slight color cast across entire image creating cohesive warm mood', badExample: '❌ "Good lighting and nice colors"', requirements: ['✓ Name color temperature', '✓ Light source that creates it', '✓ Emotional effect', '✓ How it affects other colors', '✓ Practical reasoning'], successCriteria: ['✓ Mood is clear and consistent', '✓ Color temperature unmistakable', '✓ Creates intended feeling', '✓ Professional execution']}, tools: ['Nano Banana Pro', 'Leonardo AI', 'Midjourney v8']
  },
  12: {num: 12, title: 'Day 12: Contrast and Emphasis', duration: '45 min', phase: 1, assignment: {brief: 'Use contrast to guide viewer attention', task: 'Write prompts where contrast creates clear focal points', goodExample: 'Bright white subject against dark background, creating maximum visual separation, sharp against blurred, warm against cool, large against small - multiple contrast types working together', badExample: '❌ "Good contrast"', requirements: ['✓ Type of contrast used', '✓ High/medium/subtle level', '✓ Purpose', '✓ Multiple contrast types', '✓ Result on viewer'], successCriteria: ['✓ Focal point is unmissable', '✓ Professional quality', '✓ Contrast serves purpose']}, tools: ['Nano Banana Pro', 'ChatGPT Images', 'Leonardo AI']
  },
  13: {num: 13, title: 'Day 13: Photography vs Illustration Styles', duration: '50 min', phase: 2, assignment: {brief: 'Control whether output feels photorealistic or illustrated', task: 'Write prompts that clearly specify photorealistic or illustration aesthetic', goodExample: 'Photorealistic: shot on Canon 5D, 85mm lens, f/1.8, professional product photography lighting, RAW color grading, extremely detailed and sharp vs Illustrated: digital illustration style, painterly brushstrokes, vibrant colors, slightly simplified forms, watercolor finish', badExample: '❌ "Nice realistic image"', requirements: ['✓ Photography or illustration?', '✓ Medium specifics', '✓ Camera/equipment if photo', '✓ Technique if illustration', '✓ Level of realism'], successCriteria: ['✓ Style is unmistakable', '✓ Execution matches intention', '✓ Quality is professional']}, tools: ['Nano Banana Pro', 'Leonardo AI', 'Ideogram 2.0']
  },
  14: {num: 14, title: 'Day 14: Depth and Layers', duration: '45 min', phase: 2, assignment: {brief: 'Create visual depth through layering', task: 'Write prompts with clear foreground, middle ground, background', goodExample: 'Sharp subject in foreground, softly blurred mid-ground creating depth, even softer background suggesting distance, atmospheric perspective (colors fade cooler/hazier with distance), depth of field effect, viewer perceives three-dimensional space', badExample: '❌ "Deep image with background"', requirements: ['✓ Foreground details', '✓ Middle ground treatment', '✓ Background treatment', '✓ Depth cues', '✓ Focus distribution'], successCriteria: ['✓ Clear sense of space', '✓ Three-dimensional feeling', '✓ Professional depth treatment']}, tools: ['Midjourney v8', 'Nano Banana Pro', 'Leonardo AI']
  },
  15: {num: 15, title: 'Day 15: Reflection and Phase 1 Review', duration: '60 min', phase: 1, assignment: {brief: 'Write comprehensive prompt using all 5 layers', task: 'Create a complete prompt that shows mastery of all Phase 1 concepts', goodExample: 'Professional woman (specific age/appearance), focused on meaningful work at modern desk, professional office with natural light, golden hour sunlight creates warm mood with purposeful shadows, clean contemporary aesthetic - complete prompt hitting all 5 layers, perfect hierarchy, specific colors, strong typography integration', badExample: '❌ Any generic or vague prompt from Phase 1', requirements: ['✓ All 5 layers explicit', '✓ Visual hierarchy clear', '✓ Color palette defined', '✓ Typography considered', '✓ Atmospheric details'], successCriteria: ['✓ Could generate professional-grade image', '✓ Shows clear learning progression', '✓ Demonstrates mastery of Phase 1', '✓ Portfolio-ready output']}, tools: ['Nano Banana Pro', 'Midjourney v8', 'ChatGPT Images']
  },
  16: {num: 16, title: 'Day 16: Advanced Composition Rules', duration: '50 min', phase: 2, assignment: {brief: 'Master rule of thirds, golden ratio, and dynamic composition', task: 'Write prompts using specific composition techniques', goodExample: 'Subject positioned at golden ratio intersection (not center), diagonal line leads viewer through scene, rule of thirds applied to horizon and focal point placement', badExample: '❌ "Well composed image"', requirements: ['✓ Composition rule named', '✓ Specific positioning', '✓ Geometric relationships', '✓ Visual flow', '✓ Purpose of choice'], successCriteria: ['✓ Composition feels intentional', '✓ Follows professional standards', '✓ Creates visual harmony']}, tools: ['Nano Banana Pro', 'Leonardo AI', 'Midjourney v8']
  },
  17: {num: 17, title: 'Day 17: Minimalism vs Maximalism', duration: '45 min', phase: 2, assignment: {brief: 'Consciously choose minimal or maximal aesthetic', task: 'Write prompts that clearly communicate maximalism or minimalism', goodExample: 'Minimalist: single subject, vast negative space, simple color palette (2-3 colors), clean lines, breathing room, less is more aesthetic', badExample: '❌ "Simple or complex image"', requirements: ['✓ Minimalist or maximalist?', '✓ Level of detail/elements', '✓ Space usage', '✓ Color complexity', '✓ Visual weight'], successCriteria: ['✓ Aesthetic is unmistakable', '✓ Intentional not accidental', '✓ Successful execution']}, tools: ['Nano Banana Pro', 'ChatGPT Images', 'Ideogram 2.0']
  },
  18: {num: 18, title: 'Day 18: Composition Mastery', duration: '50 min', phase: 2, assignment: {brief: 'Combine multiple composition techniques in one prompt', task: 'Write a prompt showing mastery of rule of thirds, leading lines, depth, and hierarchy all together', goodExample: 'Subject at golden ratio intersection, diagonal rock formation leads viewer through landscape, clear foreground/middle/background depth, warm golden light creates hierarchy, viewer journey clear', badExample: '❌ "Nicely composed landscape"', requirements: ['✓ Multiple techniques combined', '✓ Each serves purpose', '✓ Harmony between techniques', '✓ Creates viewer journey', '✓ Professional execution'], successCriteria: ['✓ Composition is sophisticated', '✓ Viewer path is clear', '✓ All techniques work together', '✓ Professional-grade result']}, tools: ['Midjourney v8', 'Nano Banana Pro', 'Leonardo AI']
  },
  19: {num: 19, title: 'Day 19: Mood Through Color', duration: '50 min', phase: 2, assignment: {brief: 'Use color psychology to control emotional response', task: 'Write prompts where color explicitly creates mood', requirements: ['✓ Color psychology applied', '✓ Emotional intent', '✓ Palette consistency', '✓ Specific color naming'], successCriteria: ['✓ Mood is tangible', '✓ Colors create feeling']}, tools: ['Nano Banana Pro', 'Leonardo AI', 'ChatGPT Images']
  },
  20: {num: 20, title: 'Day 20: Texture and Material Surfaces', duration: '45 min', phase: 2, assignment: {brief: 'Describe textures and materials in prompts', task: 'Write prompts where texture is a major design element', requirements: ['✓ Material names', '✓ Surface qualities', '✓ How light interacts', '✓ Visual texture effect'], successCriteria: ['✓ Textures visible in result', '✓ Material is recognizable']}, tools: ['Nano Banana Pro', 'Midjourney v8', 'Leonardo AI']
  },
  21: {num: 21, title: 'Day 21: Atmosphere and Weather', duration: '45 min', phase: 2, assignment: {brief: 'Use weather and atmospheric conditions for mood', task: 'Write prompts where atmosphere is central', requirements: ['✓ Weather condition', '✓ How it affects light', '✓ Atmospheric effect', '✓ Mood contribution'], successCriteria: ['✓ Weather is palpable', '✓ Creates mood', '✓ Affects whole image']}, tools: ['Nano Banana Pro', 'Leonardo AI', 'ChatGPT Images']
  },
  22: {num: 22, title: 'Day 22: Time of Day and Temporal Setting', duration: '45 min', phase: 2, assignment: {brief: 'Control temporal setting through light and detail', task: 'Write prompts where time period or time of day is unmistakable', requirements: ['✓ Specific time of day', '✓ Era/period if applicable', '✓ Visual cues', '✓ Light quality'], successCriteria: ['✓ Temporal setting is clear', '✓ Details support it', '✓ Cohesive throughout']}, tools: ['Nano Banana Pro', 'Midjourney v8', 'Leonardo AI']
  },
  23: {num: 23, title: 'Day 23: Cultural and Stylistic References', duration: '50 min', phase: 2, assignment: {brief: 'Draw from art movements and cultural aesthetics', task: 'Write prompts referencing specific art styles or cultural traditions', requirements: ['✓ Style/movement named', '✓ Visual characteristics', '✓ Why this reference', '✓ How to achieve it'], successCriteria: ['✓ Reference is recognizable', '✓ Authentic feeling', '✓ Appropriate application']}, tools: ['Nano Banana Pro', 'Leonardo AI', 'Ideogram 2.0']
  },
  24: {num: 24, title: 'Day 24: Phase 2 Mastery Project', duration: '60 min', phase: 2, assignment: {brief: 'Create advertising-grade image with full Phase 2 mastery', task: 'Write prompt showing all Phase 2 skills in professional context', requirements: ['✓ Advanced composition', '✓ Mood control', '✓ Style clarity', '✓ Professional execution'], successCriteria: ['✓ Advertising-grade quality', '✓ Mastery evident', '✓ Portfolio-ready']}, tools: ['Midjourney v8', 'Nano Banana Pro', 'Leonardo AI']
  },
  25: {num: 25, title: 'Day 25: Motion in Static Images', duration: '45 min', phase: 3, assignment: {brief: 'Create sense of motion in still images', task: 'Write prompts where motion is frozen but palpable', requirements: ['✓ Direction of motion', '✓ Speed implied', '✓ Momentum shown', '✓ Captured moment'], successCriteria: ['✓ Motion is tangible', '✓ Energy is visible']}, tools: ['Nano Banana Pro', 'Kling 2.6', 'Midjourney v8']
  },
  26: {num: 26, title: 'Day 26: Video Generation Prompts', duration: '50 min', phase: 3, assignment: {brief: 'Write prompts for video AI tools (Kling, Runway)', task: 'Adapt image prompts for motion video format', requirements: ['✓ Camera movement', '✓ Motion description', '✓ Timing', '✓ Start and end states'], successCriteria: ['✓ Video feels natural', '✓ Motion is smooth']}, tools: ['Kling 2.6', 'Runway Gen-4.5', 'Google Flow']
  },
  27: {num: 27, title: 'Day 27: AI Voice Narration Scripting', duration: '50 min', phase: 3, assignment: {brief: 'Write narration scripts for AI voice tools', task: 'Create scripts for ElevenLabs or Suno that pair with video', requirements: ['✓ Script quality', '✓ Pacing', '✓ Emotional tone', '✓ Length appropriate for video'], successCriteria: ['✓ Voice fits content', '✓ Timing aligns with video']}, tools: ['ElevenLabs', 'Suno v4', 'Google Gemini']
  },
  28: {num: 28, title: 'Day 28: Client Project 1 - Product Launch', duration: '90 min', phase: 4, assignment: {brief: 'Create complete campaign for product launch', task: 'Write prompts for: hero image, 3 social posts, video teaser, banner ads', requirements: ['✓ Cohesive visual language', '✓ Multiple format sizes', '✓ Consistent branding', '✓ Platform-specific'], successCriteria: ['✓ Campaign feels unified', '✓ Across all platforms', '✓ Professional quality']}, tools: ['Nano Banana Pro', 'Kling 2.6', 'ElevenLabs']
  },
  29: {num: 29, title: 'Day 29: Client Project 2 - Brand Guidelines', duration: '90 min', phase: 4, assignment: {brief: 'Create visual brand guidelines prompt deck', task: 'Document prompts that ensure brand consistency for client future use', requirements: ['✓ Style guide', '✓ Do\'s and don\'ts', '✓ Color specifications', '✓ Visual language rules'], successCriteria: ['✓ Comprehensive guide', '✓ Reusable', '✓ Clear instructions']}, tools: ['Nano Banana Pro', 'Leonardo AI', 'ChatGPT Images']
  },
  30: {num: 30, title: 'Day 30: Pricing and Delivery Formats', duration: '60 min', phase: 4, assignment: {brief: 'Understand technical requirements for client delivery', task: 'Learn about image specifications, export formats, file sizes', requirements: ['✓ Resolution knowledge', '✓ Format selection', '✓ Color space', '✓ Delivery specs'], successCriteria: ['✓ Client-ready files', '✓ Professional standards']}, tools: ['CapCut Pro', 'Adobe Photoshop', 'Figma']
  },
  31: {num: 31, title: 'Day 31: Portfolio Project 1', duration: '90 min', phase: 4, assignment: {brief: 'Create first portfolio-worthy campaign', task: 'Develop complete visual campaign for portfolio', requirements: ['✓ Professional quality', '✓ Cohesive vision', '✓ Multiple formats', '✓ Showcases skills'], successCriteria: ['✓ Portfolio-ready', '✓ Hirable quality', '✓ Tells story']}, tools: ['Nano Banana Pro', 'Midjourney v8', 'Leonardo AI']
  },
  32: {num: 32, title: 'Day 32: Portfolio Project 2', duration: '90 min', phase: 4, assignment: {brief: 'Create second distinct portfolio piece', task: 'Different style/approach than Project 1', requirements: ['✓ Shows versatility', '✓ Different aesthetic', '✓ Professional execution', '✓ Unique voice'], successCriteria: ['✓ Demonstrates range', '✓ Highest quality work']}, tools: ['Leonardo AI', 'Kling 2.6', 'ChatGPT Images']
  },
  33: {num: 33, title: 'Day 33: Phase 4 Review', duration: '60 min', phase: 4, assignment: {brief: 'Review portfolio projects and client work quality', task: 'Self-assess all Phase 4 work before moving to business', requirements: ['✓ Quality check', '✓ Consistency review', '✓ Improvement areas', '✓ Strengths identification'], successCriteria: ['✓ Portfolio-ready work', '✓ Ready for clients', '✓ Confident in abilities']}, tools: ['Figma', 'Adobe Photoshop', 'Make']
  },
  34: {num: 34, title: 'Day 34: Building Your Creator Brand', duration: '60 min', phase: 5, assignment: {brief: 'Create personal brand assets and messaging', task: 'Develop your unique positioning in AI design space', requirements: ['✓ Brand voice', '✓ Visual style', '✓ Unique angle', '✓ Target audience'], successCriteria: ['✓ Clear positioning', '✓ Authentic voice', '✓ Memorable brand']}, tools: ['Figma', 'Canva', 'Make']
  },
  35: {num: 35, title: 'Day 35: Content Creation Strategy', duration: '60 min', phase: 5, assignment: {brief: 'Plan ongoing content to showcase work', task: 'Create content calendar and prompt ideas', requirements: ['✓ Regular posting schedule', '✓ Behind-the-scenes', '✓ Process documentation', '✓ Engagement strategy'], successCriteria: ['✓ Consistent content plan', '✓ Builds audience', '✓ Showcases skills']}, tools: ['CapCut Pro', 'Google Docs', 'Make']
  },
  36: {num: 36, title: 'Day 36: Pricing Your Services', duration: '60 min', phase: 5, assignment: {brief: 'Understand AI design service pricing models', task: 'Research market rates and create your pricing structure', requirements: ['✓ Service offerings', '✓ Price points', '✓ Package options', '✓ Value communication'], successCriteria: ['✓ Competitive pricing', '✓ Value-clear', '✓ Professional structure']}, tools: ['Google Sheets', 'Make', 'Figma']
  },
  37: {num: 37, title: 'Day 37: Client Communication Templates', duration: '60 min', phase: 5, assignment: {brief: 'Create reusable client communication templates', task: 'Build email, brief, and revision request templates', requirements: ['✓ Professional tone', '✓ Clear expectations', '✓ Process documentation', '✓ Revision guidelines'], successCriteria: ['✓ Professional communication', '✓ Sets clear boundaries', '✓ Saves time']}, tools: ['Google Docs', 'Make', 'Gmail']
  },
  38: {num: 38, title: 'Day 38: Portfolio Website Build', duration: '90 min', phase: 5, assignment: {brief: 'Create portfolio website showcasing work', task: 'Build or design portfolio site (Figma mockup or live)', requirements: ['✓ Best work displayed', '✓ Case studies', '✓ Contact information', '✓ Professional design'], successCriteria: ['✓ Portfolio-ready website', '✓ Client attracting', '✓ Professional quality']}, tools: ['Figma', 'Framer', 'Make']
  },
  39: {num: 39, title: 'Day 39: Marketing and Networking', duration: '60 min', phase: 5, assignment: {brief: 'Develop marketing strategy to land clients', task: 'Identify target clients and outreach strategy', requirements: ['✓ Target audience', '✓ Outreach plan', '✓ Networking approach', '✓ Social strategy'], successCriteria: ['✓ Clear client target', '✓ Outreach ready', '✓ Networking plan']}, tools: ['LinkedIn', 'Make', 'Google Docs']
  },
  40: {num: 40, title: 'Day 40: Creating Video Showreel', duration: '90 min', phase: 5, assignment: {brief: 'Assemble portfolio work into compelling showreel', task: 'Create 60-90 second video showcasing your best work', goodExample: '60-second showreel: 3-4 hero images fade in with matching music, quick 2-second showcase of each major project, color-graded consistently, music builds toward finale, last 10 seconds show contact info, personal brand clear throughout, professional sound design', badExample: '❌ Random images with generic music', requirements: ['✓ Best work selected', '✓ Color grading consistent', '✓ Music/sound matched', '✓ Branding throughout', '✓ Clear contact info'], successCriteria: ['✓ Compelling viewing experience', '✓ Drives inquiries', '✓ Shows your style', '✓ Professional production']}, tools: ['CapCut Pro', 'Adobe Premiere Pro', 'Suno v4']
  },
  41: {num: 41, title: 'Day 41: Email Campaign Sequence', duration: '90 min', phase: 5, assignment: {brief: 'Create email campaign to get first paid clients', task: 'Write email sequence to cold/warm prospects', requirements: ['✓ Value proposition clear', '✓ Portfolio links', '✓ Call to action', '✓ Follow-up strategy', '✓ Professional tone'], successCriteria: ['✓ Generates responses', '✓ Professional quality', '✓ Results-oriented']}, tools: ['Gmail', 'Make', 'Google Docs']
  },
  42: {num: 42, title: 'Day 42: First Client Project - Part 1', duration: '120 min', phase: 5, assignment: {brief: 'Complete first paid client project', task: 'Take real or practice client brief and deliver full campaign', requirements: ['✓ Client brief understood', '✓ Multiple deliverables', '✓ Professional quality', '✓ On-time delivery', '✓ Revision process'], successCriteria: ['✓ Client satisfied', '✓ Payment received', '✓ Case study created']}, tools: ['Nano Banana Pro', 'Kling 2.6', 'Make']
  },
  43: {num: 43, title: 'Day 43: First Client Project - Part 2', duration: '120 min', phase: 5, assignment: {brief: 'Complete revisions and finalize client project', task: 'Deliver final assets and collect feedback', requirements: ['✓ Revisions incorporated', '✓ All formats delivered', '✓ Professional handoff', '✓ Client feedback collected'], successCriteria: ['✓ Client thrilled', '✓ Testimonial received', '✓ Ready for referral']}, tools: ['CapCut Pro', 'Make', 'Google Drive']
  },
  44: {num: 44, title: 'Day 44: Create Your Signature Style', duration: '120 min', phase: 5, assignment: {brief: 'Define your unique AI design voice', task: 'Develop signature aesthetic that\'s distinctly yours', goodExample: 'Your prompts consistently produce: specific color palette, lighting style, composition approach, character types, and emotional tone that\'s recognizably YOURS. Clients hire you for YOUR unique style, not generic AI outputs', badExample: '❌ Generic AI images with no consistent style', requirements: ['✓ Signature color palette', '✓ Consistent lighting approach', '✓ Recognizable composition style', '✓ Unique character aesthetic', '✓ Emotional tone'], successCriteria: ['✓ Your work is instantly recognizable', '✓ Clients want YOUR style specifically', '✓ Premium pricing justified by uniqueness', '✓ Builds long-term business']}, tools: ['Nano Banana Pro', 'Midjourney v8', 'Leonardo AI']
  },
  45: {num: 45, title: 'Day 45: The 90-Second Showreel & Your Next 90 Days', duration: '120 min', phase: 5, concept: `You\'ve completed 45 days of professional AI design education. Your showreel is your introduction to the world. The next 90 days are about execution: landing clients, building reputation, and scaling your services. You now have the skills. The question is: what will you build with them?`, assignment: {brief: 'Create final portfolio showreel and 90-day business plan', task: `1) Finalize 60-90 second showreel with your absolute best work. 2) Create 90-day plan: target 3 new clients, create 1 case study per month, grow network by 50 people, land 1 retainer client. 3) Document your pricing, positioning, and unique value.`, goodExample: '90-second showreel: cinematic opening with your best hero image (3 sec), quick montage of portfolio work (40 sec), testimonial or results (10 sec), your brand name/contact (5 sec), closes with inspiring imagery (22 sec). Music is professional, color-graded consistently, every frame represents your highest quality. Viewers immediately understand who you are and what you do. 90-day plan: January: 3 cold outreach + 2 portfolio posts/week. February: land first client + create case study. March: retainer inquiry + network event. Clear milestones.', badExample: '❌ Random collection of images with no narrative. Plan with vague goals like "get more clients" or "make more money".', requirements: ['✓ Showreel: 60-90 seconds, best work only, professional editing, music-matched', '✓ Showreel: Clear branding, contact info, memorable introduction', '✓ Plan: Specific 90-day milestones (not vague goals)', '✓ Plan: Target 3 specific client types (not "anyone")', '✓ Plan: Monthly content and networking actions', '✓ Plan: Revenue targets or retainer goals'], successCriteria: ['✓ Showreel is compelling (gets views, drives inquiries)', '✓ Showreel represents your highest quality', '✓ 90-day plan is specific and measurable', '✓ Milestones are realistic but ambitious', '✓ You\'re ready to take on paid clients confidently', '✓ Your unique style is unmistakable', '✓ You understand your market positioning']}, videos: [{title: 'How to Build Your Designer Brand', url: 'https://youtu.be/...', duration: '15 min'}, {title: 'Creating a Showreel That Gets You Hired', url: 'https://youtu.be/...', duration: '12 min'}, {title: 'Your 90-Day Launch Plan to Your First $5K Client', url: 'https://youtu.be/...', duration: '18 min'}, {title: 'Congratulations - You\'re an AI Designer Now', url: 'https://youtu.be/...', duration: '8 min'}], builder: 'portfolio-capstone', tools: ['CapCut Pro', 'Nano Banana Pro', 'Midjourney v8', 'Make', 'Figma']
  }
};

const PHASES = [
  { short: 'Foundation', long: 'Mastering the Fundamentals', dot: '#4F46E5', days: [1,2,3,4,5,6,7,8,9] },
  { short: 'Style', long: 'Visual Hierarchy & Aesthetics', dot: '#7C3AED', days: [10,11,12,13,14,15,16,17,18] },
  { short: 'Advanced', long: 'Advanced Techniques & Video', dot: '#EC4899', days: [19,20,21,22,23,24,25,26,27] },
  { short: 'Portfolio', long: 'Client Work & Portfolio Projects', dot: '#F59E0B', days: [28,29,30,31,32,33,34,35,36] },
  { short: 'Business', long: 'Launching Your AI Design Business', dot: '#10B981', days: [37,38,39,40,41,42,43,44,45] }
];
